name: Setup SSH
description: >-
  Sets up SSH access to the current runner host over a Tailscale network.

  Authentication uses the public SSH keys associated with GitHub users.  By
  default, the users who triggered the initial and current workflow runs are
  allowed.

inputs:
  tailscale-authkey:
    description: Tailscale auth key (i.e. from the admin panel); highly recommended to be ephemeral!
    required: true

  allowed-users:
    description: Comma-separated list of GitHub usernames who are allowed access via their public SSH keys.
    required: false
    default: "${{ github.triggering_actor }},${{ github.actor }}"

runs:
  using: composite
  steps:
    - name: Setup SSH
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        TAILSCALE_AUTHKEY: ${{ inputs.tailscale-authkey }}
        ALLOWED_USERS: ${{ inputs.allowed-users }}
      run: |
        # Setup SSH

        echo "::group::Debug info"
          if [[ -n "${RUNNER_DEBUG:-}" ]]; then
            ./debug-info
          fi
        echo "::endgroup::"

        echo "::group::Install Tailscale"
          curl -fsSL --proto '=https' https://tailscale.com/install.sh | sudo bash
        echo "::endgroup::"

        echo "::group::Setup Tailscale"
          ./setup-tailscale
        echo "::endgroup::"

        echo "::group::Setup SSH"
          ./setup-ssh
        echo "::endgroup::"

        ./connection-info
