name: Conda

on:
  - workflow_dispatch

jobs:
  main:
    runs-on: windows-2019
    steps:
      - uses: nextstrain/cli/.github/actions/setup-integration-tests@trs/standalone
        with:
          python-version: '3.9'
