name: Debugger

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - if: github.run_attempt > 1 && runner.debug == 1
        uses: nextstrain/.github/actions/setup-debugger@master
        with:
          tailscale-auth-key: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - run: echo start
      - run: pwd
      - run: tree
      - run: netstat -ntlp
      - run: echo end
