name: Linux containers on Windows

# https://computingforgeeks.com/how-to-run-docker-containers-on-windows-server-2019/

on:
  - workflow_dispatch

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - run: Uninstall-Package -Name docker -ProviderName DockerMSFTProvider
        continue-on-error: true
      - run: Get-VM WinContainerHost | Set-VMProcessor -ExposeVirtualizationExtensions $true
        continue-on-error: true
      - run: Install-Module DockerProvider
        continue-on-error: true
      - run: Install-Package Docker -ProviderName DockerProvider -RequiredVersion preview
        continue-on-error: true
      - run: |
          [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
        continue-on-error: true
      - run: Restart-Service docker
        continue-on-error: true
      - run: docker run -it --rm ubuntu /bin/cat /etc/os-release
        continue-on-error: true
