name: Encodings on Windows

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/encoding-win.yaml
      - print-unicode
      - click-unicode
      - rich-unicode

jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - run: python3 -m pip install click rich


      - shell: pwsh
        run: python3 print-unicode
        continue-on-error: true
      - shell: pwsh
        run: python3 click-unicode
        continue-on-error: true
      - shell: pwsh
        run: python3 rich-unicode
        continue-on-error: true

      - shell: bash
        run: python3 print-unicode
        continue-on-error: true
      - shell: bash
        run: python3 click-unicode
        continue-on-error: true
      - shell: bash
        run: python3 rich-unicode
        continue-on-error: true


      - shell: pwsh
        run: python3 -X utf8 print-unicode
        continue-on-error: true
      - shell: pwsh
        run: python3 -X utf8 click-unicode
        continue-on-error: true
      - shell: pwsh
        run: python3 -X utf8 rich-unicode
        continue-on-error: true

      - shell: bash
        run: python3 -X utf8 print-unicode
        continue-on-error: true
      - shell: bash
        run: python3 -X utf8 click-unicode
        continue-on-error: true
      - shell: bash
        run: python3 -X utf8 rich-unicode
        continue-on-error: true
      - run: python3 -X utf8 print-unicode
        shell: bash
        continue-on-error: true
