name: Encodings on Windows

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/encoding-win.yaml

jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - run: python3 -m pip install click rich

      - run: python3 print-utf8
        shell: pwsh
        continue-on-error: true

      - run: python3 print-utf8
        shell: bash
        continue-on-error: true

      - run: python3 -X utf8 print-utf8
        shell: pwsh
        continue-on-error: true

      - run: python3 -X utf8 print-utf8
        shell: bash
        continue-on-error: true
