name: interpolation

on:
  workflow_dispatch:
    inputs:
      string:
        type: string
        default: ""
        required: false

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - env:
          string: ${{ inputs.string }}
        run: env
        shell: bash
