name: oidc
on:
  workflow_dispatch:
jobs:
  x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            let idToken = await core.getIDToken();
            let unvalidatedClaims = JSON.parse(atob(idToken.split(".", 2)[1]));
            console.log(unvalidatedClaims);
