name: Pathogen repo build

on: workflow_dispatch

jobs:
  run-build:
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build-exploded.yaml@trs/pathogen-repo-build/wait-for-aws-batch-job
    with:
      repo: nextstrain/zika-tutorial
      runtime: aws-batch
      run: nextstrain build --detach --env X=X .
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
