name: Python on Windows

on:
  - workflow_dispatch

jobs:
  main:
    name: python=${{ matrix.python }} os=${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        python:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          activate-environment: test

      - run: env
      - run: type python
      - run: python --version
      - run: type python3
      - run: python3 --version

      - run: |
          python="$(type -p python)"
          cp -v "$python" "$(dirname "$python")"/python3

      - run: type python3
      - run: python3 --version
