name: reusable
on:
  workflow_call:
    inputs:
      ref:
        type: string
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -lR .
      - run: env
      - run: ps aux
      - run: echo "$0"; cat "$0"
      - run: echo "${{ github.step_summary }}"; cat "${{ github.step_summary }}"
      - run: echo "github=$json"
        env:
          json: |
            ${{ toJSON(github) }}
      - run: echo "env=$json"
        env:
          json: |
            ${{ toJSON(env) }}
      - run: echo "job=$json"
        env:
          json: |
            ${{ toJSON(job) }}
      - run: echo "inputs=$json"
        env:
          json: |
            ${{ toJSON(inputs) }}
