name: reusable
on:
  workflow_call:
    inputs:
      ref:
        type: string
jobs:
  x:
    runs-on: ubuntu-latest
    steps:
      - id: job-instance
        name: ${{ steps.job-instance.outputs.uuid }}
        run: |
          echo "::set-output name=uuid::$(python3 -c 'from uuid import uuid4; print(uuid4())')"

      #- name: ${{ steps.job-instance.outputs.uuid }}
      #  run: echo "job instance is ${{ steps.job-instance.outputs.uuid }}"

      - run: |
          sleep 5
          curl -fsSiL https://api.github.com/repos/"$GITHUB_REPOSITORY"/actions/runs/"$GITHUB_RUN_ID"/jobs -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

      - run: pwd
      - run: ls -lR .
      - run: ls -lR /home/runner/work
      - run: env
      - run: ps aux
      - run: echo "$0"; cat "$0"
      - run: echo "${{ github.step_summary }}"; cat "${{ github.step_summary }}"
      - run: cat "$file"
        env:
          file: "/home/runner/work/_PipelineMapping/${{ github.repository }}/PipelineFolder.json"
      - run: echo "github=$json"
        env:
          json: |
            ${{ toJSON(github) }}
      - run: echo "env=$json"
        env:
          json: |
            ${{ toJSON(env) }}
      - run: echo "job=$json"
        env:
          json: |
            ${{ toJSON(job) }}
      - run: echo "inputs=$json"
        env:
          json: |
            ${{ toJSON(inputs) }}
