name: Tailscale SSH

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup-ssh
        with:
          tailscale-authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Sit and wait…
        shell: bash
        run: |
          while [[ ! -e ~/quit ]]; do
            sleep 15
          done
