name: Tailscale SSH

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ip addr
          ip route
        continue-on-error: true
        
      - uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh

      - run: |
          mkdir -p ~/.ssh
          curl -fsSL --proto '=https' https://github.com/{${{ github.triggering_actor }},${{ github.actor }}}.keys > ~/.ssh/authorized_keys

      - run: while [[ ! -e ~/quit ]]; do sleep 30; done
