name: uses working directory
on:
  workflow_dispatch:
jobs:
  job: 
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -v repo
      - uses: actions/checkout@v3
        working-directory: repo
      - run: ls -l repo
